robot_physics:
  base_mass: 1.0
  chassis_mass: 0.3
  wheel_mass: 0.05
  caster_mass: 0.02
  wheel_damping: 0.5
  wheel_friction: 0.05
  caster_damping: 1.0
  caster_friction: 0.1
  max_wheel_torque: 3.0
  max_wheel_acceleration: 0.6
  max_linear_velocity: 1.0
  max_angular_velocity: 2.0
  diff_update_rate: 50
  jsp_update_rate: 30
  drive_mu: 1.0
  caster_mu: 0.02
  drive_slip: 0.12
  caster_slip: 0.95
  drive_kp: 300.0
  caster_kp: 50.0
  drive_kd: 10.0
  caster_kd: 8.0
  base_ixx_factor: 0.002
  base_iyy_factor: 0.002
  base_izz_factor: 0.003
  wheel_ixx_factor: 1.0e-05
  wheel_iyy_factor: 1.0e-05
  wheel_izz_factor: 2.0e-05
  caster_yr_ixx: 3.1184e-06
  caster_yr_iyy: 3.1184e-06
  caster_yr_izz: 6.195e-06
  caster_p_ixx: 8.26e-06
  caster_p_iyy: 8.26e-06
  caster_p_izz: 8.26e-06
