robot_physics:
  base_mass: null
  chassis_mass: 0.4
  wheel_mass: 0.05
  caster_mass: 0.05
  wheel_damping: 1.0
  wheel_friction: 1.0
  caster_damping: 0.0
  caster_friction: 0.1
  max_wheel_torque: 1.0
  max_wheel_acceleration: 2.5
  max_linear_velocity: 1.9
  max_angular_velocity: 6.0
  diff_update_rate: 20
  jsp_update_rate: 20
  drive_mu: 1.0
  caster_mu: 0.01
  drive_slip: 0.005
  caster_slip: 0.95
  drive_kp: 5600
  caster_kp: 1000
  drive_kd: 50.0
  caster_kd: 20.0
  base_ixx_factor: null
  base_iyy_factor: null
  base_izz_factor: null
  wheel_ixx_factor: 0.0003451
  wheel_iyy_factor: 0.0003451
  wheel_izz_factor: 0.0006
  caster_yr_ixx: 0.00031184
  caster_yr_iyy: 0.00031184
  caster_yr_izz: 0.0006195
  caster_p_ixx: 0.000826
  caster_p_iyy: 0.000826
  caster_p_izz: 0.000826
