robot_physics:
  base_mass:
  chassis_mass:
  wheel_mass:
  caster_mass:
  wheel_damping:
  wheel_friction:
  caster_damping:
  caster_friction:
  max_wheel_torque:
  max_wheel_acceleration:
  max_linear_velocity:
  max_angular_velocity:
  diff_update_rate:
  jsp_update_rate:
  drive_mu:
  caster_mu:
  drive_slip:
  caster_slip:
  drive_kp:
  caster_kp:
  drive_kd:
  caster_kd:
  base_ixx_factor:
  base_iyy_factor:
  base_izz_factor:
  wheel_ixx_factor:
  wheel_iyy_factor:
  wheel_izz_factor:
  caster_yr_ixx:
  caster_yr_iyy:
  caster_yr_izz:
  caster_p_ixx:
  caster_p_iyy:
  caster_p_izz:
